### ISSUE TITLE
Script killed after screen is locked

### ISSUE THREAD

**Issue by slavid** [slavid/razer-mouse-dock-color-battery#1]
Running Pop!_OS with Gnome 42

If running the script as a startup program like so: `/usr/bin/python3 /path/to/razer-battery-colors.py &`  and I lock the screen, after a few minutes, when unlocked, the script is no longer running.

As a workaround while I find the root cause I have switched to using scrontab and calling the script every minute (`* * * * * /path/to/crontab-razer-battery-colors.py >/dev/null 2>&1`).

**Comment by slavid** [comment]
Getting errors like these:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/crontab-razer-battery-colors.py", line 10, in <module>
    devicemgr = DeviceManager()
  File "/usr/lib/python3/dist-packages/openrazer/client/__init__.py", line 22, in __init__
    session_bus = _dbus.SessionBus()
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

I had to change how the crontab works so that I can have the variable `DBUS_SESSION_BUS_ADDRESS` exported.

I created a shell script that calls the Python script called `razer-battery-launcher.sh`:

```bash
#!/bin/sh

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

/usr/bin/python3 /path/to/crontab-razer-battery-colors.py
```
Where `1000` is your user id (you can check your user id with the command `$ id` and copy the number after uid `uid=1000`).

Changed crontab to:

```
* * * * * /path/to/razer-battery-launcher.sh >/dev/null 2>&1
```

And now it seems to be working fine.

**Comment by slavid** [comment]
Solution to script no longer running after the screen is locked:

Make sure `devices_off_on_screensaver` is set to `False` in `razer.conf` file located at `/home/$USER/.config/openrazer`.

This will keep the devices running thus preventing driver fails and keeping the script running.
